@include("admin.common.input_file",array('var'=>'logo','width'=>300,'height'=>80))
@include("admin.common.input_select",array('var'=>'category','col'=>$categories))
@include("admin.common.input_select",array('var'=>'owner_id','col'=>$owners))
@include("admin.common.input_select",array('var'=>'parent_id','col'=>$locations))
@include("admin.common.input_text",array('var'=>'name'))
@include("admin.common.input_text",array('var'=>'phone'))
@include("admin.common.input_hidden",array('var'=>'latitude'))
@include("admin.common.input_hidden",array('var'=>'longitude'))
@include("admin.common.input_select",array('var'=>'countries_id','col'=>$countries))
@include("admin.common.input_text",array('var'=>'timezone'))
@include("admin.common.input_text",array('var'=>'website'))
@include("admin.common.input_text",array('var'=>'maillist'))
@include("admin.common.input_text",array('var'=>'address'))
@include("admin.common.input_number",array('var'=>'screen_timer'))

